
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java  CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build-java:

    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
   
    - name: Test with Gradle
      run: ./gradlew test

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-jar
        path: build/libs/*.jar
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and tag Docker image
       run:|
          docker build -t venkat7624/demoapp:latest .
          docker images ls
   
    - name: Push Docker image to Docker Hub
        run:docker push venkat7624/demoapp:latest

    - name: Remove Docker images locally
        run:docker image rm venkat7624/demoapp:latest
